/* include/libssh2_config.h.  Generated by configure.  */
/* include/libssh2_config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define HAVE_SYS_UIO_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Enable "none" cipher -- NOT RECOMMENDED */
/* #undef LIBSSH2_CRYPT_NONE */

/* Output connection layer debugging info to stderr */
/* #undef LIBSSH2_DEBUG_CONNECTION */
//#define LIBSSH2_DEBUG_CONNECTION

/* Output failure events to stderr */
/* #undef LIBSSH2_DEBUG_ERRORS */

/* Output Key Exchange debugging info to stderr */
/* #undef LIBSSH2_DEBUG_KEX */

/* Output publickey subsystem debugging info to stderr */
/* #undef LIBSSH2_DEBUG_PUBLICKEY */

/* Output scp subsystem debugging info to stderr */
/* #undef LIBSSH2_DEBUG_SCP */

/* Output sftp subsystem debugging info to stderr */
/* #undef LIBSSH2_DEBUG_SFTP */

/* Output transport layer debugging info to stderr */
/* #undef LIBSSH2_DEBUG_TRANSPORT */

/* Output userauth layer debugging info to stderr */
/* #undef LIBSSH2_DEBUG_USERAUTH */

/* Enable newer diffie-hellman-group-exchange-sha1 syntax */
#define LIBSSH2_DH_GEX_NEW 1

/* Compile in zlib support */
#define LIBSSH2_HAVE_ZLIB 1

/* Enable "none" MAC -- NOT RECOMMENDED */
/* #undef LIBSSH2_MAC_NONE */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sarag@libssh2.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libssh2"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libssh2 0.14"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libssh2"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.14"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
#define WORDS_BIGENDIAN 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
